---
kind: pipeline
name: louvain-native

steps:
- name: publish-deploy
  image: plugins/gcr
  settings:
    json_key:
      from_secret: GCR_TOKEN
    registry: eu.gcr.io
    repo: eu.gcr.io/graphext-0/louvain
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: e6eadc46ad2161cb158cc7148b770ef56579926d31627263a1ba2112cee84c6b

...
