[package]
name = "louvain"
version = "0.1.0"
authors = ["Juan Morales <crispamares@gmail.com>"]

[dependencies]
chrono = "*"

serde = "*"
serde_json = "*"
serde_derive = "*"

rand = "*"
petgraph = "*"
