[package]
name = "louvain"
version = "0.1.0"
authors = ["Juan Morales <crispamares@gmail.com>"]

[dependencies]
chrono = "0.4"

serde = "1"
serde_json = "1"
serde_derive = "1"

rand = "0.5"
petgraph = "0.4"
fnv = "1"
slotmap = {version = "0.3", features = ["unstable"]}