[package]
name = "louvain"
version = "0.1.0"
authors = ["Juan Morales <crispamares@gmail.com>"]

[dependencies]
chrono = "*"

serde = "1"
serde_json = "1"
serde_derive = "1"

rand = "*"
petgraph = "*"
