[package]
name = "louvain_asmjs"
version = "0.1.0"
authors = ["Juan Morales <crispamares@gmail.com>"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
stdweb = "0.1.1"
louvain = { path = ".." }
petgraph = "*"

chrono = "*"